### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by robertwritescode** [binarylogic/settingslogic#15]
Hello,

I'm working on a website that will rely heavily on reading from settingslogic and I was wondering if settingslogic comes with built in caching and if it does not, how should I implement it?

Regards,
Robert

**Comment by ghost** [comment]
I don't think theres a need for this. Settinglogic is nothing more than a hash, its cached in memory. Are you need more than that?

**Comment by robertwritescode** [comment]
Exactly what I was looking for! Thank you :)
