### ISSUE TITLE
deep nested keys not pulled out correctly via method call approach

### ISSUE THREAD

**Issue by ak47** [binarylogic/settingslogic#2]
example yaml,

development:
    bucket:
      master:
        pr: pcdlnv-mstr-dev
        qa: pcdlnv-mstr-dev-qa
      manifest:
        pr: pcdlnv-mfst-dev
        qa: pcdlnv-mfst-dev-qa
      message:
        pr: pcdlnv-msg-dev
        qa: pcdlnv-msg-dev-qa

now in script/console

> > Settings.s3.bucket.message
> > => {"pr"=>"pcdlnv-msg-dev", "qa"=>"pcdlnv-msg-dev-qa"}
> > Settings.s3.bucket.message.pr
> > => "pcdlnv-mstr-dev"
> > Settings.s3.bucket.message['pr']
> > => "pcdlnv-msg-dev"

when calling the value using the dotting method it gets the wrong value, but using Hash key is correct

**Comment by ghost** [comment]
I wrote some tests, and I can't duplicate the issue. Want to write in your own tests and see if you can do it? Check this out:

http://github.com/binarylogic/settingslogic/commit/e9271139c5a0d7f93b7406a98c8d8019a374263d

**Comment by ak47** [comment]
the ambiguity is when two child keys have the same value

I forked and made a test, http://github.com/ak47/settingslogic/tree/master

here's what I get

andy@pdd-andy-mbp (master)->spec spec/settingslogic_spec.rb 
.....F..

1)
'Settingslogic should access other extra deep nested settings' FAILED
expected: 5,
     got: 2 (using ==)
./spec/settingslogic_spec.rb:25:

Finished in 0.044861 seconds

8 examples, 1 failure

it sets the child key name as a method, the one that gets set first has that method name to return it's value

example from above yml,

> > Settings.s3.bucket.master
> > /Users/andy/gits/tonopah/vendor/gems/settingslogic-2.0.2/lib/settingslogic.rb:63
> > self.class.send(:define_method, name) { value }
> > (rdb:1) c
> > => {"pr"=>"pcdlnv-mstr-dev", "qa"=>"pcdlnv-mstr-dev-qa"}
> > Settings.s3.bucket.master.qa
> > => "pcdlnv-msg-dev-qa"
> > Settings.s3.bucket.qa
> > => "pcdlnv-msg-dev-qa"
> > Settings.s3.qa
> > => "pcdlnv-msg-dev-qa"
> > Settings.qa
> > => "pcdlnv-msg-dev-qa"

it doesn't matter what precedes the 'qa' call

**Comment by aaronchi** [comment]
I was having the same issue. Can't use the new version

**Comment by ghost** [comment]
I pulled in some changes to fix this. Thanks.
