### ISSUE TITLE
Add default config options

### ISSUE THREAD

**Issue by skateinmars** [binarylogic/settingslogic#3]
Hello,

I'd like to see an easy way to have default options, stored directly on the model (or maybe optionally on another config file).

After a quick glance on the source code it seems to be doable by manually looking for the key (or calling method_missing ?), but I guess this would be a hack.

Is there any plan to do this ?

Thanks !

**Comment by ayanko** [comment]
Implemented!

https://github.com/binarylogic/settingslogic/pull/16

Waiting for author ...

**Comment by skateinmars** [comment]
This issue is likely outdated so I'm closing this.
