### ISSUE TITLE
Eval (string)? 

### ISSUE THREAD

**Issue by rutgerg** [binarylogic/settingslogic#39]
Thanks for this gem. Question: I"m using settingslogic for setting expires_in setting in memcache eg

Rails.cache.fetch("Time_now", :expires_in => Settings.expires_in) {Time.now}

if I set the expires_in in the application.yml it will be a string eg 2.minutes which will not be understood by Memcached. The way I currently make this work is do 

Rails.cache.fetch("Time_now", :expires_in => eval(Settings.expires_in)) {Time.now}

Is this the way to go or does anybody have a better solution?

**Comment by goosetav** [comment]
settingslogic runs the file through erb before processing it, just set your value like this:

```
defaults:
  expires_in: <%= 2.minutes %>
```

**Comment by rutgerg** [comment]
Txs
