### ISSUE TITLE
Uninitialized constant error

### ISSUE THREAD

**Issue by dlangerenken** [binarylogic/settingslogic#48]
Hey, i followed your documentation and implemented in the exactly same way.
I can't access the model. I get a name-error "uninitialized constant Properties ("i've tried other names too, because of probably name-conflicts) - nothing works :(

how can i access it? :/

**Comment by everm1nd** [comment]
same crap in my libs

**Comment by ryanburnette** [comment]
I'm having the same issue. I'm sure that I missed a step in the instructions. Curious to know what solves the issue though.
