### ISSUE TITLE
Alias parsing was not enabled in ruby3.2

### ISSUE THREAD

**Issue by minorun99** [binarylogic/settingslogic#87]
In ruby3.2, the following error occurs.
```
Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`. (Psych::AliasesNotEnabled)
```

**Comment by minorun99** [comment]
Already exists.

**Comment by zousu** [comment]
https://github.com/settingslogic/settingslogic/blob/463073f8c42fa9b5d976ccd5b8c98f433a18f42e/lib/settingslogic.rb#L105

`hash = file_contents.empty? ? {} : YAML.load(ERB.new(file_contents).result, aliases: true).to_hash`


add aliases: true, Remove the gem and place the file settingslogic.rb in app/lib
